### ISSUE TITLE
error after last tekken patch

### ISSUE THREAD

**Issue by sweetclimusic** [roguelike2d/TekkenBot#28]
program runs but soone as fight starts erros out.

No fight detected. Gamestate not updated.
No fight detected. Gamestate not updated.
No fight detected. Gamestate not updated.
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1559, in __call__
  File "tkinter\__init__.py", line 605, in callit
  File "GUI_FrameDataOverlay.py", line 205, in update_launcher
  File "_FrameDataLauncher.py", line 16, in Update
  File "TekkenEncyclopedia.py", line 131, in Update
TypeError: GetOppTechnicalStates() missing 1 required positional argument: 'startup'

**Comment by roguelike2d** [comment]
Build should be fixed now.
