### ISSUE TITLE
tekken pid not acquired error

### ISSUE THREAD

**Issue by Yamato12345** [roguelike2d/TekkenBot#69]
This is what I'n getting when I try to launch the app. In windowed mode currently, not sure what else to do.
Tekken pid not acquired. Trying to acquire...
Tekken pid not acquired. Trying to acquire...Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1559, in __call__
  File "tkinter\__init__.py", line 605, in callit
  File "GUI_TekkenBotPrime.py", line 212, in update_launcher
  File "_FrameDataLauncher.py", line 13, in Update
  File "TekkenGameState.py", line 539, in Update
  File "TekkenGameState.py", line 161, in GetUpdatedState
  File "GUI_TekkenBotPrime.py", line 247, in write
  File "GUI_TekkenBotPrime.py", line 127, in write_to_overlay
  File "GUI_FrameDataOverlay.py", line 84, in write
  File "tkinter\__init__.py", line 3123, in index
_tkinter.TclError: invalid command name ".97959160.98527384"

**Comment by compsyguy** [comment]
Are you using the latest version of TekkenBot? Also are you using the compiled version or are you running it from source?

**Comment by compsyguy** [comment]
The compiled version you double click the program, the source version you have to run python from the command line. If you don't know you're probably using the compiled version.

Did you get your version from here:
https://github.com/WAZAAAAA0/TekkenBot
?

**Comment by Yamato12345** [comment]
I had to run it as admin with compatibility for it to work, not sure why but at least it finds the game now.
